apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-access-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-access
  template:
    metadata:
      labels:
        app: secret-access
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "cat /etc/secrets/my-key"]
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
